version: '2'
services:
  web:
    build: .
    command: yarn start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://postgress@postgres/app
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgress
      POSTGRES_DB: app
  redis:
    image: redis:4