version: '3'

services:
  web:
    build: .
    command: bash -c "/usr/app/wait-for-it.sh db:5432 -- /usr/app/node_modules/.bin/sequelize db:migrate && /usr/app/node_modules/.bin/sequelize db:seed:all & yarn start"
    # command: "/wait-for-it.sh", "db:5432", "--", "yarn", "start"]
    volumes:
      - .:/usr/app/
    ports:
      - "3001:3001"
    depends_on:
      - db
      - redis
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=poe-currency-flipper
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
